### PR TITLE
Update joss lcz namelist

### PR DESCRIPTION
**Pull request by matthiasdemuzere**
Adding:
- reference to global map of LCZs
- additional information to set use_wudapt_lcz = 1 and num_land_cat = 41.

### CODE REVIEW

**Comment by matthiasdemuzere** [comment]
I am now waiting for the global LCZ map to go in review. Once it does, it will get a DOI, I can then update the reference, and merge this branch.

**Review by theendlessriver13 — APPROVED** [review]

**Comment by matthiasdemuzere** [comment]
@theendlessriver13: I have updated the reference to the global LCZ map in the JOSS paper.
Can you review this, and if fine, merge into main?

Once done, perhaps you can also bump the version number and update the pip repo?
If no time, I can try this myself using your tutorial.

Once all of this is in place, I'll re-submit to JOSS!

**Review by theendlessriver13 — APPROVED** [review]
Looks all good!

I don't think we need to make a release to PyPi, since no actual code changed since the release of `0.2.0` (https://github.com/matthiasdemuzere/w2w/compare/0.2.0...update_joss_lcz_namelist). So no files included in the sdist or wheel would be changed.

I think we're ready to resubmit 🤞

**Pull request merged**
