### PR TITLE
fix spaces in user-defined ucp lookup table

### PR DESCRIPTION
**Pull request by matthiasdemuzere**
Addressing the white spaces in column names of user-defined LCZ look-up table. See #92

### CODE REVIEW

**Comment by matthiasdemuzere** [comment]
I have added a small check to see whether the custom MH_URB2D_MIN (MH_URB2D_MAX) values are smaller (larger) than MH_URB2D. Which is needed to calculate the building height distribution with `scipy.stats.truncnorm`.

This integrity check is only executed when a custom ucp table is provided.

**Comment by theendlessriver13** [comment]
I just added a test for this and found very minor bug. The name of the index becomes something like this `'     '` where it should be `None`.  I don't think this is relevant for us, but not sure if we can just ignore it.

**Comment by matthiasdemuzere** [comment]
Just wondering @theendlessriver13, are you still working on this? As far as I can see, the test is failing?

**Comment by theendlessriver13** [comment]
> I just added a test for this and found a very minor bug. The name of the index becomes something like this `' '` where it should be `None`. I don't think this is relevant for us, but not sure if we can/should just ignore it.

This is still the question because the Implementation is not 100% correct, that's why the new test fails.

**Comment by matthiasdemuzere** [comment]
I see... so I will have to check my implementation. Will add to my todo list ...

**Comment by matthiasdemuzere** [comment]
This fixes this small (irrelevant) mismatch between the dataframes! @theendlessriver13

**Pull request merged**
